### ISSUE TITLE
The sample works partially on all the browsers

### ISSUE THREAD

**Issue by neeraj87** [brandiqa/simplewebrtc-messenger#1]
The example is not working completely anywhere. Tested it on Chrome, Firefox and Safari. Sometimes the person can see other but cannot hear, sometimes they cannot see other but hear them..varying results. The chat however works on all three.

**Comment by brandiqa** [comment]
There are many points of failure with WebRTC. 

- You need to allow camera and microphone permissions on both ends
- The connection needs to be https, otherwise video/audio connection won't be allowed
- You'll need sufficient upload speeds on both ends. At least 0.5Mbps should work fine
- There might be an issue with the default TURN servers, or something with the configuration
- I highly recommend you use Chrome. Try testing with a chrome desktop browser and chrome mobile browser within the same local network
- A firewall or a proxy server in the network may be preventing the video/audio traffic for passing through

Plus many other issues I haven't thought of.

The truth is, implementing a stable WebRTC solution is not easy. Do check out this site for more information on this: https://www.simplewebrtc.com/

P.S.Do check you are using the latest version of simplewebrtc.

**Comment by neeraj87** [comment]
Thanks for the prompt reply Michael. I loved your demo and it is helpful. I will go through the mentioned items and see whats going on.
